import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import { AppNavbar } from "@/components/layout/navbar";
import { cn } from "@/lib/utils";
import { Footer } from "@/components/dynamic-zone/footer";
import { Timeline } from "@/components/ui/timeline";
import { data, TimelineData } from "@/constants/timelinedata";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const timelinedata: TimelineData[] = data;
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <div
          className={cn(
            inter.className,
            'bg-charcoal antialiased h-full w-full'
          )}
        >
          <ViewTransitions >
            <AppNavbar />
            {children}
            <Timeline data={timelinedata} />
            <Footer />
          </ViewTransitions>
        </div>
      </body>
    </html>
  );
}
